[[beans-child-bean-definitions]]
= Bean Definition Inheritance

빈 정의에는 생성자 인자, 속성 값, 초기화 메소드, 정적 팩토리 메소드 이름 등과 같은 컨테이너 특정 정보를 포함한 많은 구성 정보가 포함될 수 있습니다. 자식 빈 정의는 부모 정의로부터 구성 데이터를 상속받습니다. 자식 정의는 필요에 따라 일부 값을 덮어쓰거나 다른 값을 추가할 수 있습니다. 부모 및 자식 빈 정의를 사용하면 많은 타이핑을 절약할 수 있습니다. 실질적으로 이것은 템플릿 형태의 하나입니다.

프로그래밍 방식으로 `ApplicationContext` 인터페이스와 작업할 때, 자식 빈 정의는 `ChildBeanDefinition` 클래스로 표현됩니다. 대부분의 사용자는 이 수준에서 작업하지 않습니다. 대신, `ClassPathXmlApplicationContext`와 같은 클래스에서 선언적으로 빈 정의를 구성합니다. XML 기반 구성 메타데이터를 사용할 때, `parent` 속성을 사용하여 자식 빈 정의를 나타낼 수 있으며, 이 속성의 값으로 부모 빈을 지정합니다. 다음 예제는 이를 수행하는 방법을 보여줍니다.:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="inheritedTestBean" abstract="true"
			class="org.springframework.beans.TestBean">
		<property name="name" value="parent"/>
		<property name="age" value="1"/>
	</bean>

	<bean id="inheritsWithDifferentClass"
			class="org.springframework.beans.DerivedTestBean"
			parent="inheritedTestBean" init-method="initialize">  <1>
		<property name="name" value="override"/>
		<!-- the age property value of 1 will be inherited from parent -->
	</bean>
----
<1> `parent` 속성에 주목하세요.

자식 빈 정의는 지정되지 않은 경우 부모 정의의 빈 클래스를 사용하지만, 이를 덮어쓸 수도 있습니다. 후자의 경우, 자식 빈 클래스는 부모와 호환되어야 합니다(즉, 부모의 속성 값들을 받아들일 수 있어야 합니다).

자식 빈 정의는 범위, 생성자 인자 값, 속성 값, 메소드 오버라이드를 부모로부터 상속받으며, 새로운 값을 추가할 수 있는 옵션을 가집니다. 지정하는 범위, 초기화 메소드, 파괴 메소드 또는 `static` 팩토리 메소드 설정은 해당 부모 설정을 덮어씁니다.

나머지 설정은 항상 자식 정의에서 가져옵니다: depends on, autowire 모드, 의존성 검사, 싱글톤, 그리고 지연 초기화.

앞의 예제에서는 `abstract` 속성을 사용하여 부모 빈 정의를 명시적으로 추상으로 표시합니다. 부모 정의가 클래스를 지정하지 않은 경우, 부모 빈 정의를 `abstract`로 명시적으로 표시하는 것이 필요합니다. 다음 예제에서 보여주는 것과 같습니다.:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="inheritedTestBeanWithoutClass" abstract="true">
		<property name="name" value="parent"/>
		<property name="age" value="1"/>
	</bean>

	<bean id="inheritsWithClass" class="org.springframework.beans.DerivedTestBean"
			parent="inheritedTestBeanWithoutClass" init-method="initialize">
		<property name="name" value="override"/>
		<!-- age will inherit the value of 1 from the parent bean definition-->
	</bean>
----

부모 빈은 불완전하기 때문에 혼자서 인스턴스화될 수 없으며, `abstract`로 명시적으로 표시됩니다. 정의가 `abstract`인 경우, 그것은 순수한 템플릿 빈 정의로만 사용 가능하며, 자식 정의의 부모 정의로서 기능합니다. 이러한 `abstract` 부모 빈을 혼자 사용하려고 하면, 즉 다른 빈의 ref 속성으로 참조하거나 부모 빈 ID로 명시적인 `getBean()` 호출을 하는 것은 오류를 반환합니다. 마찬가지로, 컨테이너의 내부 `preInstantiateSingletons()` 메소드는 `abstract`로 정의된 빈 정의를 무시합니다.

참고: `ApplicationContext`는 기본적으로 모든 싱글톤을 사전 인스턴스화합니다. 따라서, 당신이 오직 템플릿으로만 사용할 의도로 (부모) 빈 정의를 가지고 있고, 이 정의가 클래스를 지정하는 경우, __abstract__ 속성을 __true__로 설정해야 합니다. 그렇지 않으면 애플리케이션 컨텍스트는 실제로 `abstract` 빈을 (시도하여) 사전 인스턴스화하려 할 것입니다(적어도 싱글톤 빈에 대해서는 중요합니다).



---
[[beans-child-bean-definitions]]
= Bean Definition Inheritance

A bean definition can contain a lot of configuration information, including constructor
arguments, property values, and container-specific information, such as the initialization
method, a static factory method name, and so on. A child bean definition inherits
configuration data from a parent definition. The child definition can override some
values or add others as needed. Using parent and child bean definitions can save a lot
of typing. Effectively, this is a form of templating.

If you work with an `ApplicationContext` interface programmatically, child bean
definitions are represented by the `ChildBeanDefinition` class. Most users do not work
with them on this level. Instead, they configure bean definitions declaratively in a class
such as the `ClassPathXmlApplicationContext`. When you use XML-based configuration
metadata, you can indicate a child bean definition by using the `parent` attribute,
specifying the parent bean as the value of this attribute. The following example shows how
to do so:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="inheritedTestBean" abstract="true"
			class="org.springframework.beans.TestBean">
		<property name="name" value="parent"/>
		<property name="age" value="1"/>
	</bean>

	<bean id="inheritsWithDifferentClass"
			class="org.springframework.beans.DerivedTestBean"
			parent="inheritedTestBean" init-method="initialize">  <1>
		<property name="name" value="override"/>
		<!-- the age property value of 1 will be inherited from parent -->
	</bean>
----
<1> Note the `parent` attribute.

A child bean definition uses the bean class from the parent definition if none is
specified but can also override it. In the latter case, the child bean class must be
compatible with the parent (that is, it must accept the parent's property values).

A child bean definition inherits scope, constructor argument values, property values, and
method overrides from the parent, with the option to add new values. Any scope, initialization
method, destroy method, or `static` factory method settings that you specify
override the corresponding parent settings.

The remaining settings are always taken from the child definition: depends on,
autowire mode, dependency check, singleton, and lazy init.

The preceding example explicitly marks the parent bean definition as abstract by using
the `abstract` attribute. If the parent definition does not specify a class, explicitly
marking the parent bean definition as `abstract` is required, as the following example
shows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="inheritedTestBeanWithoutClass" abstract="true">
		<property name="name" value="parent"/>
		<property name="age" value="1"/>
	</bean>

	<bean id="inheritsWithClass" class="org.springframework.beans.DerivedTestBean"
			parent="inheritedTestBeanWithoutClass" init-method="initialize">
		<property name="name" value="override"/>
		<!-- age will inherit the value of 1 from the parent bean definition-->
	</bean>
----

The parent bean cannot be instantiated on its own because it is incomplete, and it is
also explicitly marked as `abstract`. When a definition is `abstract`, it is
usable only as a pure template bean definition that serves as a parent definition for
child definitions. Trying to use such an `abstract` parent bean on its own, by referring
to it as a ref property of another bean or doing an explicit `getBean()` call with the
parent bean ID returns an error. Similarly, the container's internal
`preInstantiateSingletons()` method ignores bean definitions that are defined as
abstract.

NOTE: `ApplicationContext` pre-instantiates all singletons by default. Therefore, it is
important (at least for singleton beans) that if you have a (parent) bean definition
which you intend to use only as a template, and this definition specifies a class, you
must make sure to set the __abstract__ attribute to __true__, otherwise the application
context will actually (attempt to) pre-instantiate the `abstract` bean.





