[[beans-definition]]
= Bean Overview

Spring IoC 컨테이너는 하나 이상의 빈을 관리합니다. 이러한 빈들은 컨테이너에 제공한 구성 메타데이터에 따라 (예: XML `<bean/>` 정의 형식으로) 생성됩니다.

컨테이너 내에서 이러한 빈 정의는 `BeanDefinition` 객체로 표현되며, 다음과 같은 메타데이터를 포함합니다:

- 패키지 자격 이름: 일반적으로 빈의 실제 구현 클래스의 이름입니다.
- 빈의 동작 구성 요소: 빈이 컨테이너에서 어떻게 동작해야 하는지에 대한 정보(범위, 라이프사이클 콜백 등).
- 빈이 작업을 수행하는 데 필요한 다른 빈에 대한 참조. 이러한 참조는 협력자 또는 의존성으로도 불립니다.
- 새로 생성된 객체에 설정할 다른 구성 설정(예: 풀의 크기 또는 연결 풀을 관리하는 빈에서 사용할 연결 수 등).

이러한 메타데이터는 각 빈 정의를 구성하는 속성 집합으로 변환됩니다. 다음 표에서는 이러한 속성을 설명합니다:

[[beans-factory-bean-definition-tbl]]
.빈 정의
|===
| 속성| 설명

| Class
| xref:core/beans/definition.adoc#beans-factory-class[빈 생성]

| Name
| xref:core/beans/definition.adoc#beans-beanname[빈 이름]

| Scope
| xref:core/beans/factory-scopes.adoc[빈 범위]

| 생성자 인자
| xref:core/beans/dependencies/factory-collaborators.adoc[의존성 주입]

| 속성
| xref:core/beans/dependencies/factory-collaborators.adoc[의존성 주입]

| Autowiring 모드
| xref:core/beans/dependencies/factory-autowire.adoc[자동 와이어링 협력자]

| 지연 초기화 모드
| xref:core/beans/dependencies/factory-lazy-init.adoc[지연 초기화된 빈]

| 초기화 메서드
| xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-initializingbean[초기화 콜백]

| 소멸 메서드
| xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-disposablebean[소멸 콜백]
|===

빈 정의 메타데이터뿐만 아니라 컨테이너 외부(사용자에 의해)에서 생성된 기존 객체의 등록도 `ApplicationContext` 구현에서 허용됩니다. 
이는 `getBeanFactory()` 메서드를 통해 `DefaultListableBeanFactory` 구현을 반환하는 `ApplicationContext`의 `BeanFactory`에 액세스하여 수행됩니다. 
`DefaultListableBeanFactory`는 `registerSingleton(..)` 및 `registerBeanDefinition(..)` 메서드를 통해 이 등록을 지원합니다. 그러나 일반적인 응용 프로그램은 보통 정규 빈 정의 메타데이터를 통해 정의된 빈들과만 작동합니다.

[NOTE]
====
빈 메타데이터와 수동으로 제공된 싱글톤 인스턴스는 가능한 한 빨리 등록되어야 합니다. 이렇게 하면 컨테이너가 자동 와이어링 및 기타 내사 검사 단계 중에 이들을 올바르게 처리할 수 있습니다. 기존 메타데이터 및 기존 싱글톤 인스턴스를 일부로 오버라이딩하는 것은 어느 정도 지원되지만, 런타임에서 새로운 빈을 등록하는 것(팩토리에 라이브 액세스와 동시에)은 공식적으로 지원되지 않으며 동시 액세스 예외, 빈 컨테이너의 일관되지 않은 상태 또는 이 두 가지 모두의 결과로 이어질 수 있습니다.
====

[[beans-beanname]]
== Naming Beans

모든 빈은 하나 이상의 식별자를 가지고 있어야 합니다. 이러한 식별자들은 빈을 호스팅하는 컨테이너 내에서 고유해야 합니다. 빈은 보통 하나의 식별자만 가집니다. 그러나 하나 이상의 식별자가 필요한 경우 추가 식별자는 별칭으로 간주할 수 있습니다.

XML 기반의 구성 메타데이터에서 빈 식별자를 지정하려면 `id` 속성, `name` 속성 또는 둘 다를 사용합니다. `id` 속성은 하나의 `id`를 지정하도록 허용합니다. 
일반적으로 이러한 이름은 알파벳과 숫자로 이루어져 있습니다('myBean', 'someService' 등), 하지만 특수 문자도 포함할 수 있습니다. 
빈에 대한 다른 별칭을 도입하려면 `name` 속성에서 쉼표(','), 세미콜론(';'), 공백으로 구분하여 지정할 수도 있습니다. 
`id` 속성은 `xsd:string` 타입으로 정의되어 있지만 빈 `id`의 고유성은 컨테이너에 의해 강제되며 XML 파서에 의해 강제되지 않습니다.

빈에 대한 `name` 또는 `id`를 제공하는 것은 필수가 아닙니다. `name` 또는 `id`를 명시적으로 제공하지 않는 경우 컨테이너는 해당 빈에 대해 고유한 이름을 생성합니다. 그러나 그 빈을 이름으로 참조하려면 `ref` 요소나 서비스 로케이터 스타일 조회를 통해 이름을 제공해야 합니다.
`name`을 제공하지 않는 이유는 xref:core/beans/dependencies/factory-properties-detailed.adoc#beans-inner-beans[내부 빈(inner beans)] 및 xref:core/beans/dependencies/factory-autowire.adoc[자동 와이어링(collaborators)]을 사용하는 것과 관련이 있습니다.

빈 네이밍 컨벤션

빈 이름을 지정할 때 표준 Java 컨벤션을 사용하는 것이 일반적입니다. 즉, 빈 이름은 소문자로 시작하고 camelCase로 작성됩니다. 이러한 이름의 예로는 `accountManager`, `accountService`, `userDao`, `loginController` 등이 있습니다.

빈의 이름을 일관되게 지정하면 구성을 읽고 이해하기 쉬워집니다. 또한 Spring AOP를 사용하는 경우 이름별로 관련된 빈 집합에 조언을 적용할 때 매우 도움이 됩니다.

참고: 클래스 패스에 컴포넌트 스캐닝이 있는 경우 Spring은 이름이 지정되지 않은 컴포넌트에 대한 빈 이름을 생성하며, 앞에서 설명한 규칙을 따릅니다. 이 규칙은 기본적으로 클래스 이름을 가져와서 첫 문자를 소문자로 바꾸는 것입니다. 그러나 (특별한 경우로서) 첫 번째와 두 번째 문자가 모두 대문자인 경우 원래 대소문자가 유지됩니다. 이는 Spring이 여기에서 사용하는 `java.beans.Introspector.decapitalize`에 정의된 규칙과 동일합니다.

[[beans-beanname-alias]]
=== Aliasing a Bean outside the Bean Definition

빈 정의 내에서는 `id` 속성으로 지정된 하나의 이름과 `name` 속성으로 지정된 여러 개의 이름을 조합하여 빈에 대해 여러 개의 이름을 지정할 수 있습니다. 이러한 이름들은 동일한 빈에 대한 동등한 별칭이 될 수 있으며, 각 구성 요소가 애플리케이션에서 고유한 의존성을 참조할 수 있도록 하는 경우와 같이 일부 상황에 유용합니다.

그러나 빈이 실제로 정의된 위치에서 모든 별칭을 지정하는 것이 항상 충분하지는 않을 수 있습니다. 대형 시스템에서는 구성이 각 서브시스템 간에 분할되고 각 서브시스템에는 고유한 객체 정의 세트가 있으므로 다른 곳에서 정의된 빈에 대한 별칭을 도입하는 것이 종종 필요합니다. XML 기반 구성 메타데이터에서는 이를 수행하기 위해 `<alias/>` 요소를 사용할 수 있습니다. 다음 예제에서는 이를 보여줍니다.

```xml
<alias name="fromName" alias="toName"/>
```

이 경우, 동일한 컨테이너 내에서 `fromName`이라는 빈은 이 별칭 정의를 사용한 후에도 `toName`으로 참조될 수 있습니다.

예를 들어, 서브시스템 A의 구성 메타데이터는 `subsystemA-dataSource`라는 이름으로 DataSource를 참조할 수 있습니다. 서브시스템 B의 구성 메타데이터는 `subsystemB-dataSource`라는 이름으로 DataSource를 참조할 수 있습니다. 이 두 서브시스템을 사용하는 주요 애플리케이션을 작성할 때, 주요 애플리케이션은 `myApp-dataSource`라는 이름으로 DataSource를 참조할 수 있습니다. 이 세 가지 이름이 모두 동일한 객체를 참조하도록 하려면 다음과 같이 구성 메타데이터에 별칭 정의를 추가할 수 있습니다.

```xml
<alias name="myApp-dataSource" alias="subsystemA-dataSource"/>
<alias name="myApp-dataSource" alias="subsystemB-dataSource"/>
```

이제 각 구성 요소와 주요 애플리케이션은 고유한 이름으로 dataSource를 참조할 수 있으며 다른 정의와 충돌하지 않는 것이 보장됩니다(사실상 네임스페이스를 만들어내는 것), 그런데 이들은 모두 동일한 빈을 참조합니다.

.Java 구성
****
Java 구성을 사용하는 경우 `@Bean` 주석을 사용하여 별칭을 제공할 수 있습니다. 자세한 내용은 xref:core/beans/java/bean-annotation.adoc[`@Bean` 주석 사용]을 참조하십시오.
****

[[beans-factory-class]]
== Instantiating Beans

빈 정의는 사실 하나 이상의 객체를 생성하기 위한 레시피입니다. 컨테이너는 빈의 이름이 요청될 때 해당 빈 정의의 레시피를 살펴보고, 빈 정의에 의해 캡슐화된 구성 메타데이터를 사용하여 실제 객체를 생성(또는 획득)합니다.

XML 기반 구성 메타데이터를 사용하는 경우, `<bean/>` 요소의 `class` 속성에서 생성될 객체의 유형(또는 클래스)을 지정합니다. 이 `class` 속성(내부적으로는 `BeanDefinition` 인스턴스의 `Class` 속성)은 일반적으로 필수입니다. (예외 사항은 xref:core/beans/definition.adoc#beans-factory-class-instance-factory-method[인스턴스 팩토리 메서드를 사용한 인스턴스화] 및 xref:core/beans/child-bean-definitions.adoc[빈 정의 상속]을 참조하십시오.)
`Class` 속성은 다음 두 가지 방식으로 사용할 수 있습니다.

* 일반적으로 컨테이너 자체가 빈을 생성하기 위해 빈 클래스를 지정하는 경우에 사용됩니다. 컨테이너는 빈을 생성하기 위해 생성자를 반사적으로 호출하며, 이것은 `new` 연산자를 사용한 Java 코드와 어느 정도 유사합니다.
* 빈을 생성하기 위해 컨테이너가 클래스에서 `static` 팩토리 메서드를 호출하는 덜 일반적인 경우에는 실제 클래스를 지정합니다. `static` 팩토리 메서드의 호출에서 반환되는 객체 유형은 동일한 클래스 또는 다른 클래스일 수 있습니다.

.중첩 클래스 이름
****
중첩 클래스에 대한 빈 정의를 구성하려면 중첩 클래스의 이진 이름 또는 소스 이름을 모두 사용할 수 있습니다.

예를 들어, `com.example` 패키지에 `SomeThing`라는 클래스가 있고 이 `SomeThing` 클래스에 `static` 중첩 클래스인 `OtherThing`이 있다면, 이들은 달러 기호(`$`)나 점(`.`)으로 구분할 수 있습니다. 따라서 빈 정의의 `class` 속성의 값은 `com.example.SomeThing$OtherThing` 또는 `com.example.SomeThing.OtherThing`가 될 것입니다.
****

[[beans-factory-class-ctor]]
=== Instantiation with a Constructor

빈을 생성하는 경우, 모든 일반 클래스는 Spring과 호환되며 Spring이 사용 가능합니다. 즉, 개발 중인 클래스는 특정 인터페이스를 구현하거나 특정한 방식으로 코드화할 필요가 없습니다. 단순히 빈 클래스를 지정하는 것으로 충분합니다. 그러나 특정한 빈에 대해 어떤 종류의 IoC를 사용하느냐에 따라 기본(빈 생성자가 없는) 생성자가 필요할 수 있습니다.

Spring IoC 컨테이너는 원하는 거의 모든 클래스를 관리할 수 있습니다. 진정한 JavaBeans를 관리하는 것에 제한되지 않습니다. 대부분의 Spring 사용자는 컨테이너의 속성을 모델링한 기본(인자 없는) 생성자와 적절한 설정자(Getter) 및 설정 메서드(Setter)를 가진 실제 JavaBeans를 선호합니다. 또한 JavaBean 규격을 준수하지 않는 레거시 연결 풀을 사용해야 하는 경우와 같이 더 다양한 형식의 클래스도 컨테이너에 포함시킬 수 있습니다. 이 경우 Spring은 그것을 관리할 수 있습니다.

XML 기반 구성 메타데이터를 사용하는 경우, 빈 클래스를 다음과 같이 지정할 수 있습니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="exampleBean" class="examples.ExampleBean"/>

<bean name="anotherExample" class="examples.ExampleBeanTwo"/>
----

생성자에 인수를 제공하는 메커니즘 및 객체 인스턴스 속성을 객체가 생성된 후 설정하는 자세한 내용은 xref:core/beans/dependencies/factory-collaborators.adoc[의존성 주입]을 참조하십시오.


[[beans-factory-class-static-factory-method]]
=== Instantiation with a Static Factory Method

`static` 팩토리 메서드로 생성하는 빈을 정의할 때, `class` 속성을 사용하여 `static` 팩토리 메서드를 포함한 클래스를 지정하고 `factory-method`라는 속성을 사용하여 팩토리 메서드의 이름을 지정합니다. 이 메서드를 호출하고 (나중에 설명할 선택적 인수와 함께) 라이브 객체를 반환해야 하며, 반환된 객체는 이후에 생성자를 통해 생성된 것처럼 처리됩니다. 이러한 빈 정의의 한 가지 사용 예는 레거시 코드에서 `static` 팩토리를 호출하는 것입니다.

다음의 빈 정의는 팩토리 메서드를 호출하여 빈이 생성됨을 지정합니다. 이 정의는 반환된 객체의 유형(클래스)을 지정하는 대신 팩토리 메서드를 포함한 클래스를 지정합니다. 이 예에서 `createInstance()` 메서드는 `static` 메서드여야 합니다. 다음 예제는 팩토리 메서드를 지정하는 방법을 보여줍니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="clientService"
	class="examples.ClientService"
	factory-method="createInstance"/>
----

다음 예제는 이전 빈 정의와 함께 작동하는 클래스를 보여줍니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public class ClientService {
	private static ClientService clientService = new ClientService();
	private ClientService() {}

	public static ClientService createInstance() {
		return clientService;
	}
}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
class ClientService private constructor() {
	companion object {
		private val clientService = ClientService()
		@JvmStatic
		fun createInstance() = clientService
	}
}
----
======

팩토리 메서드에 (선택적) 인수를 제공하고, 객체가 팩토리에서 반환된 후에 객체 인스턴스 속성을 설정하는 메커니즘에 대한 자세한 내용은 xref:core/beans/dependencies/factory-properties-detailed.adoc[자세한 의존성 및 구성]을 참조하십시오.

[[beans-factory-class-instance-factory-method]]
=== Instantiation by Using an Instance Factory Method

`static` 팩토리 메서드를 통한 인스턴스화와 유사하게, 인스턴스 팩토리 메서드를 사용하여 컨테이너 내에서 기존 빈의 비정적(non-static) 메서드를 호출하여 새 빈을 생성합니다. 이 메커니즘을 사용하려면 `class` 속성을 비워두고 `factory-bean` 속성에 현재 컨테이너(또는 부모 또는 상위 컨테이너)에 있는 빈의 이름을 지정하여 객체를 생성하기 위해 호출될 인스턴스 메서드를 포함하는 빈의 이름을 `factory-method` 속성으로 설정합니다. 다음 예제는 이러한 빈을 구성하는 방법을 보여줍니다:

```xml
<!-- 팩토리 메서드를 포함하는 factory bean -->
<bean id="serviceLocator" class="examples.DefaultServiceLocator">
    <!-- 이 로케이터 빈이 필요로 하는 종속성 주입 -->
</bean>

<!-- 팩토리 메서드를 통해 생성될 빈 -->
<bean id="clientService"
    factory-bean="serviceLocator"
    factory-method="createClientServiceInstance"/>
```

다음 예제는 해당 클래스를 보여줍니다:

**Java:**
```java
public class DefaultServiceLocator {

    private static ClientService clientService = new ClientServiceImpl();

    public ClientService createClientServiceInstance() {
        return clientService;
    }
}
```

**Kotlin:**
```kotlin
class DefaultServiceLocator {

    companion object {
        private val clientService = ClientServiceImpl()
    }

    fun createClientServiceInstance(): ClientService {
        return clientService
    }
}
```

하나의 팩토리 클래스는 여러 개의 팩토리 메서드를 보유할 수도 있으며, 다음 예제에서처럼 보여질 수 있습니다:

```xml
<bean id="serviceLocator" class="examples.DefaultServiceLocator">
    <!-- 이 로케이터 빈이 필요로 하는 종속성 주입 -->
</bean>

<bean id="clientService"
    factory-bean="serviceLocator"
    factory-method="createClientServiceInstance"/>

<bean id="accountService"
    factory-bean="serviceLocator"
    factory-method="createAccountServiceInstance"/>
```

다음 예제는 해당 클래스를 보여줍니다:

**Java:**
```java
public class DefaultServiceLocator {

    private static ClientService clientService = new ClientServiceImpl();
    private static AccountService accountService = new AccountServiceImpl();

    public ClientService createClientServiceInstance() {
        return clientService;
    }

    public AccountService createAccountServiceInstance() {
        return accountService;
    }
}
```

**Kotlin:**
```kotlin
class DefaultServiceLocator {

    companion object {
        private val clientService = ClientServiceImpl()
        private val accountService = AccountServiceImpl()
    }

    fun createClientServiceInstance(): ClientService {
        return clientService
    }

    fun createAccountServiceInstance(): AccountService {
        return accountService
    }
}
```

이 접근 방식은 팩토리 빈 자체가 종속성 주입(DI)을 통해 관리되고 구성될 수 있다는 것을 보여줍니다. 자세한 내용은 [의존성과 구성 자세히 알아보기](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-dependencies-detailed)를 참조하십시오.

**참고**: Spring 문서에서 "factory bean"은 Spring 컨테이너에서 구성되고 `instance` 또는 `static` 팩토리 메서드를 통해 객체를 생성하는 빈을 가리킵니다. 반면에 `FactoryBean` (대문자 구분에 유의)은 Spring 특정 `FactoryBean` 구현 클래스를 가리킵니다.

[[beans-factory-type-determination]]
=== Determining a Bean's Runtime Type

특정 빈의 런타임 유형을 결정하는 것은 간단하지 않습니다. 빈 메타데이터 정의에서 지정된 클래스는 초기 클래스 참조일 뿐이며, 선언된 팩토리 메서드와 결합되거나 `FactoryBean` 클래스가 될 수 있으며, 경우에 따라 지정된 `factory-bean` 이름을 통해 해결되는 인스턴스 수준의 팩토리 메서드의 경우에는 설정되지 않을 수도 있습니다. 또한, AOP 프록시가 인터페이스 기반 프록시로 빈 인스턴스를 래핑할 수 있으며 이 경우에는 대상 빈의 실제 유형(구현된 인터페이스만 노출)만 노출됩니다.

특정 빈의 실제 런타임 유형을 확인하는 권장 방법은 지정된 빈 이름에 대한 `BeanFactory.getType` 호출입니다. 이렇게 하면 위에서 설명한 모든 경우를 고려하고 `BeanFactory.getBean` 호출이 동일한 빈 이름에 대해 반환할 객체의 유형을 반환합니다.

---

[[beans-definition]]
= Bean Overview

A Spring IoC container manages one or more beans. These beans are created with the
configuration metadata that you supply to the container (for example, in the form of XML
`<bean/>` definitions).

Within the container itself, these bean definitions are represented as `BeanDefinition`
objects, which contain (among other information) the following metadata:

* A package-qualified class name: typically, the actual implementation class of the
  bean being defined.
* Bean behavioral configuration elements, which state how the bean should behave in the
  container (scope, lifecycle callbacks, and so forth).
* References to other beans that are needed for the bean to do its work. These
  references are also called collaborators or dependencies.
* Other configuration settings to set in the newly created object -- for example, the size
  limit of the pool or the number of connections to use in a bean that manages a
  connection pool.

This metadata translates to a set of properties that make up each bean definition.
The following table describes these properties:

[[beans-factory-bean-definition-tbl]]
.The bean definition
|===
| Property| Explained in...

| Class
| xref:core/beans/definition.adoc#beans-factory-class[Instantiating Beans]

| Name
| xref:core/beans/definition.adoc#beans-beanname[Naming Beans]

| Scope
| xref:core/beans/factory-scopes.adoc[Bean Scopes]

| Constructor arguments
| xref:core/beans/dependencies/factory-collaborators.adoc[Dependency Injection]

| Properties
| xref:core/beans/dependencies/factory-collaborators.adoc[Dependency Injection]

| Autowiring mode
| xref:core/beans/dependencies/factory-autowire.adoc[Autowiring Collaborators]

| Lazy initialization mode
| xref:core/beans/dependencies/factory-lazy-init.adoc[Lazy-initialized Beans]

| Initialization method
| xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-initializingbean[Initialization Callbacks]

| Destruction method
| xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-disposablebean[Destruction Callbacks]
|===

In addition to bean definitions that contain information on how to create a specific
bean, the `ApplicationContext` implementations also permit the registration of existing
objects that are created outside the container (by users). This is done by accessing the
ApplicationContext's `BeanFactory` through the `getBeanFactory()` method, which returns
the `DefaultListableBeanFactory` implementation. `DefaultListableBeanFactory` supports
this registration through the `registerSingleton(..)` and `registerBeanDefinition(..)`
methods. However, typical applications work solely with beans defined through regular
bean definition metadata.

[NOTE]
====
Bean metadata and manually supplied singleton instances need to be registered as early
as possible, in order for the container to properly reason about them during autowiring
and other introspection steps. While overriding existing metadata and existing
singleton instances is supported to some degree, the registration of new beans at
runtime (concurrently with live access to the factory) is not officially supported and may
lead to concurrent access exceptions, inconsistent state in the bean container, or both.
====



[[beans-beanname]]
== Naming Beans

Every bean has one or more identifiers. These identifiers must be unique within the
container that hosts the bean. A bean usually has only one identifier. However, if it
requires more than one, the extra ones can be considered aliases.

In XML-based configuration metadata, you use the `id` attribute, the `name` attribute, or
both to specify bean identifiers. The `id` attribute lets you specify exactly one `id`.
Conventionally, these names are alphanumeric ('myBean', 'someService', etc.), but they
can contain special characters as well. If you want to introduce other aliases for the
bean, you can also specify them in the `name` attribute, separated by a comma (`,`),
semicolon (`;`), or white space. Although the `id` attribute is defined as an
`xsd:string` type, bean `id` uniqueness is enforced by the container, though not by XML
parsers.

You are not required to supply a `name` or an `id` for a bean. If you do not supply a
`name` or `id` explicitly, the container generates a unique name for that bean. However,
if you want to refer to that bean by name, through the use of the `ref` element or a
Service Locator style lookup, you must provide a name.
Motivations for not supplying a name are related to using xref:core/beans/dependencies/factory-properties-detailed.adoc#beans-inner-beans[inner beans]
 and xref:core/beans/dependencies/factory-autowire.adoc[autowiring collaborators].

.Bean Naming Conventions
****
The convention is to use the standard Java convention for instance field names when
naming beans. That is, bean names start with a lowercase letter and are camel-cased
from there. Examples of such names include `accountManager`,
`accountService`, `userDao`, `loginController`, and so forth.

Naming beans consistently makes your configuration easier to read and understand.
Also, if you use Spring AOP, it helps a lot when applying advice to a set of beans
related by name.
****

NOTE: With component scanning in the classpath, Spring generates bean names for unnamed
components, following the rules described earlier: essentially, taking the simple class name
and turning its initial character to lower-case. However, in the (unusual) special
case when there is more than one character and both the first and second characters
are upper case, the original casing gets preserved. These are the same rules as
defined by `java.beans.Introspector.decapitalize` (which Spring uses here).


[[beans-beanname-alias]]
=== Aliasing a Bean outside the Bean Definition

In a bean definition itself, you can supply more than one name for the bean, by using a
combination of up to one name specified by the `id` attribute and any number of other
names in the `name` attribute. These names can be equivalent aliases to the same bean
and are useful for some situations, such as letting each component in an application
refer to a common dependency by using a bean name that is specific to that component
itself.

Specifying all aliases where the bean is actually defined is not always adequate,
however. It is sometimes desirable to introduce an alias for a bean that is defined
elsewhere. This is commonly the case in large systems where configuration is split
amongst each subsystem, with each subsystem having its own set of object definitions.
In XML-based configuration metadata, you can use the `<alias/>` element to accomplish
this. The following example shows how to do so:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<alias name="fromName" alias="toName"/>
----

In this case, a bean (in the same container) named `fromName` may also,
after the use of this alias definition, be referred to as `toName`.

For example, the configuration metadata for subsystem A may refer to a DataSource by the
name of `subsystemA-dataSource`. The configuration metadata for subsystem B may refer to
a DataSource by the name of `subsystemB-dataSource`. When composing the main application
that uses both these subsystems, the main application refers to the DataSource by the
name of `myApp-dataSource`. To have all three names refer to the same object, you can
add the following alias definitions to the configuration metadata:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<alias name="myApp-dataSource" alias="subsystemA-dataSource"/>
	<alias name="myApp-dataSource" alias="subsystemB-dataSource"/>
----

Now each component and the main application can refer to the dataSource through a name
that is unique and guaranteed not to clash with any other definition (effectively
creating a namespace), yet they refer to the same bean.

.Java-configuration
****
If you use Java Configuration, the `@Bean` annotation can be used to provide aliases.
See xref:core/beans/java/bean-annotation.adoc[Using the `@Bean` Annotation] for details.
****



[[beans-factory-class]]
== Instantiating Beans

A bean definition is essentially a recipe for creating one or more objects. The
container looks at the recipe for a named bean when asked and uses the configuration
metadata encapsulated by that bean definition to create (or acquire) an actual object.

If you use XML-based configuration metadata, you specify the type (or class) of object
that is to be instantiated in the `class` attribute of the `<bean/>` element. This
`class` attribute (which, internally, is a `Class` property on a `BeanDefinition`
instance) is usually mandatory. (For exceptions, see
xref:core/beans/definition.adoc#beans-factory-class-instance-factory-method[Instantiation by Using an Instance Factory Method] and xref:core/beans/child-bean-definitions.adoc[Bean Definition Inheritance].)
You can use the `Class` property in one of two ways:

* Typically, to specify the bean class to be constructed in the case where the container
  itself directly creates the bean by calling its constructor reflectively, somewhat
  equivalent to Java code with the `new` operator.
* To specify the actual class containing the `static` factory method that is
  invoked to create the object, in the less common case where the container invokes a
  `static` factory method on a class to create the bean. The object type returned
  from the invocation of the `static` factory method may be the same class or another
  class entirely.

.Nested class names
****
If you want to configure a bean definition for a nested class, you may use either the
binary name or the source name of the nested class.

For example, if you have a class called `SomeThing` in the `com.example` package, and
this `SomeThing` class has a `static` nested class called `OtherThing`, they can be
separated by a dollar sign (`$`) or a dot (`.`). So the value of the `class` attribute in
a bean definition would be `com.example.SomeThing$OtherThing` or
`com.example.SomeThing.OtherThing`.
****


[[beans-factory-class-ctor]]
=== Instantiation with a Constructor

When you create a bean by the constructor approach, all normal classes are usable by and
compatible with Spring. That is, the class being developed does not need to implement
any specific interfaces or to be coded in a specific fashion. Simply specifying the bean
class should suffice. However, depending on what type of IoC you use for that specific
bean, you may need a default (empty) constructor.

The Spring IoC container can manage virtually any class you want it to manage. It is
not limited to managing true JavaBeans. Most Spring users prefer actual JavaBeans with
only a default (no-argument) constructor and appropriate setters and getters modeled
after the properties in the container. You can also have more exotic non-bean-style
classes in your container. If, for example, you need to use a legacy connection pool
that absolutely does not adhere to the JavaBean specification, Spring can manage it as
well.

With XML-based configuration metadata you can specify your bean class as follows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean"/>

	<bean name="anotherExample" class="examples.ExampleBeanTwo"/>
----

For details about the mechanism for supplying arguments to the constructor (if required)
and setting object instance properties after the object is constructed, see
xref:core/beans/dependencies/factory-collaborators.adoc[Injecting Dependencies].


[[beans-factory-class-static-factory-method]]
=== Instantiation with a Static Factory Method

When defining a bean that you create with a static factory method, use the `class`
attribute to specify the class that contains the `static` factory method and an attribute
named `factory-method` to specify the name of the factory method itself. You should be
able to call this method (with optional arguments, as described later) and return a live
object, which subsequently is treated as if it had been created through a constructor.
One use for such a bean definition is to call `static` factories in legacy code.

The following bean definition specifies that the bean will be created by calling a
factory method. The definition does not specify the type (class) of the returned object,
but rather the class containing the factory method. In this example, the
`createInstance()` method must be a `static` method. The following example shows how to
specify a factory method:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="clientService"
		class="examples.ClientService"
		factory-method="createInstance"/>
----

The following example shows a class that would work with the preceding bean definition:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class ClientService {
		private static ClientService clientService = new ClientService();
		private ClientService() {}

		public static ClientService createInstance() {
			return clientService;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class ClientService private constructor() {
		companion object {
			private val clientService = ClientService()
			@JvmStatic
			fun createInstance() = clientService
		}
	}
----
======

For details about the mechanism for supplying (optional) arguments to the factory method
and setting object instance properties after the object is returned from the factory,
see xref:core/beans/dependencies/factory-properties-detailed.adoc[Dependencies and Configuration in Detail].


[[beans-factory-class-instance-factory-method]]
=== Instantiation by Using an Instance Factory Method

Similar to instantiation through a xref:core/beans/definition.adoc#beans-factory-class-static-factory-method[static factory method]
, instantiation with an instance factory method invokes a non-static
method of an existing bean from the container to create a new bean. To use this
mechanism, leave the `class` attribute empty and, in the `factory-bean` attribute,
specify the name of a bean in the current (or parent or ancestor) container that contains
the instance method that is to be invoked to create the object. Set the name of the
factory method itself with the `factory-method` attribute. The following example shows
how to configure such a bean:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- the factory bean, which contains a method called createClientServiceInstance() -->
	<bean id="serviceLocator" class="examples.DefaultServiceLocator">
		<!-- inject any dependencies required by this locator bean -->
	</bean>

	<!-- the bean to be created via the factory bean -->
	<bean id="clientService"
		factory-bean="serviceLocator"
		factory-method="createClientServiceInstance"/>
----

The following example shows the corresponding class:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class DefaultServiceLocator {

		private static ClientService clientService = new ClientServiceImpl();

		public ClientService createClientServiceInstance() {
			return clientService;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class DefaultServiceLocator {
		companion object {
			private val clientService = ClientServiceImpl()
		}
		fun createClientServiceInstance(): ClientService {
			return clientService
		}
	}
----
======

One factory class can also hold more than one factory method, as the following example shows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="serviceLocator" class="examples.DefaultServiceLocator">
		<!-- inject any dependencies required by this locator bean -->
	</bean>

	<bean id="clientService"
		factory-bean="serviceLocator"
		factory-method="createClientServiceInstance"/>

	<bean id="accountService"
		factory-bean="serviceLocator"
		factory-method="createAccountServiceInstance"/>
----

The following example shows the corresponding class:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class DefaultServiceLocator {

		private static ClientService clientService = new ClientServiceImpl();

		private static AccountService accountService = new AccountServiceImpl();

		public ClientService createClientServiceInstance() {
			return clientService;
		}

		public AccountService createAccountServiceInstance() {
			return accountService;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class DefaultServiceLocator {
		companion object {
			private val clientService = ClientServiceImpl()
			private val accountService = AccountServiceImpl()
		}

		fun createClientServiceInstance(): ClientService {
			return clientService
		}

		fun createAccountServiceInstance(): AccountService {
			return accountService
		}
	}
----
======

This approach shows that the factory bean itself can be managed and configured through
dependency injection (DI). See xref:core/beans/dependencies/factory-properties-detailed.adoc[Dependencies and Configuration in Detail]
.

NOTE: In Spring documentation, "factory bean" refers to a bean that is configured in the
Spring container and that creates objects through an
xref:core/beans/definition.adoc#beans-factory-class-instance-factory-method[instance] or
xref:core/beans/definition.adoc#beans-factory-class-static-factory-method[static] factory method. By contrast,
`FactoryBean` (notice the capitalization) refers to a Spring-specific
xref:core/beans/factory-extension.adoc#beans-factory-extension-factorybean[`FactoryBean`] implementation class.


[[beans-factory-type-determination]]
=== Determining a Bean's Runtime Type

The runtime type of a specific bean is non-trivial to determine. A specified class in
the bean metadata definition is just an initial class reference, potentially combined
with a declared factory method or being a `FactoryBean` class which may lead to a
different runtime type of the bean, or not being set at all in case of an instance-level
factory method (which is resolved via the specified `factory-bean` name instead).
Additionally, AOP proxying may wrap a bean instance with an interface-based proxy with
limited exposure of the target bean's actual type (just its implemented interfaces).

The recommended way to find out about the actual runtime type of a particular bean is
a `BeanFactory.getType` call for the specified bean name. This takes all of the above
cases into account and returns the type of object that a `BeanFactory.getBean` call is
going to return for the same bean name.







