[[beans-factory-autowire]]
= Autowiring Collaborators

Spring 컨테이너는 협력하는 빈들 간의 관계를 자동으로 연결할 수 있습니다. 
Spring은 빈의 내용을 검사하여 빈에 대한 협력자(다른 빈들)를 자동으로 해결하게 할 수 있습니다.
자동 와이어링은 다음과 같은 이점이 있습니다:

* Autowiring은 속성 또는 생성자 인수를 지정하는 필요성을 크게 줄일 수 있습니다. (다른 메커니즘, 예를 들어 이 장의 다른 부분에서 설명하는 빈 템플릿 xref:core/beans/child-bean-definitions.adoc[discussed elsewhere in this chapter] 같은 것들도 이러한 측면에서 유용합니다.)
* Autowiring은 객체가 진화할 때 구성을 업데이트할 수 있습니다. 예를 들어 클래스에 의존성을 추가해야 할 때, 해당 의존성을 구성을 수정하지 않고도 자동으로 해결할 수 있습니다. 따라서 autowiring은 개발 중에 특히 유용하며 코드 기반이 더 안정화된 후 명시적인 와이어링으로 전환하는 옵션을 제거하지 않습니다.

XML 기반 구성 메타데이터를 사용할 때 (<bean/> 요소의 autowire 속성 참조) 빈 정의의 자동와이어링 모드를 지정할 수 있습니다. 자동와이어링 기능에는 네 가지 모드가 있습니다. 빈마다 자동와이어링을 지정하므로 어떤 것을 자동와이어링할지 선택할 수 있습니다. 다음 표는 네 가지 자동와이어링 모드를 설명합니다:

[[beans-factory-autowiring-modes-tbl]]
.Autowiring modes
[cols="20%,80%"]
|===
| Mode| Explanation

| `no`
| (기본값) 자동와이어링 없음. 빈 참조는 ref 요소에 의해 정의되어야 합니다. 대규모 배포에서는 기본 설정을 변경하는 것이 권장되지 않습니다. 외부 협력자를 명시적으로 지정하는 것이 더 큰 제어와 명확성을 제공합니다. 어느 정도로는 시스템의 구조를 문서화합니다.

| `byName`
| 속성 이름에 의한 자동와이어링. 스프링은 자동와이어링이 필요한 속성과 동일한 이름을 가진 빈을 찾습니다. 예를 들어, 빈 정의가 이름별로 자동와이어링되도록 설정되어 있고 `master` 속성을 포함하는 경우 (즉, `setMaster(..)` 메서드가 있는 경우), 스프링은 `master`라는 이름의 빈 정의를 찾아 속성을 설정하는 데 사용합니다.

| `byType`
| 정확히 속성 유형의 빈이 컨테이너에 하나만 존재하는 경우 해당 속성을 자동 와이어링합니다. 하나 이상이 존재하는 경우에는 치명적인 예외가 발생하며 해당 빈에 대해 `byType` 자동 와이어링을 사용할 수 없음을 나타냅니다. 일치하는 빈이 없으면 아무런 동작도 수행되지 않으며 (속성은 설정되지 않음).

| `constructor`
| `byType`과 유사하지만 생성자 인수에 적용됩니다. 생성자 인수 유형의 빈이 컨테이너에 정확히 하나가 아닌 경우 치명적인 오류가 발생합니다.
|===

`byType` 또는 `constructor` 자동 연결 모드로 배열 및 형식화된 컬렉션을 연결할 수 있습니다. 
이러한 경우 컨테이너 내에서 기대하는 유형과 일치하는 모든 자동 연결 대상이 의존성을 충족하기 위해 제공됩니다. 
예상된 키 유형이 `String`인 경우 강력한 형식화된 `Map` 인스턴스를 자동으로 연결할 수 있습니다.
자동 연결된 `Map` 인스턴스의 값은 예상된 유형과 일치하는 모든 빈 인스턴스이며, `Map` 인스턴스의 키에는 해당하는 빈 이름이 포함됩니다.

[[beans-autowired-exceptions]]
== Limitations and Disadvantages of Autowiring

자동 와이어링은 프로젝트 전체에서 일관되게 사용될 때 가장 잘 작동합니다.
일반적으로 자동 와이어링을 사용하지 않는 경우, 자동 와이어링을 하나 또는 두 개의 빈 정의에만 적용하는 것은 개발자에게 혼란스러울 수 있습니다.

자동 와이어링의 제한사항과 단점을 고려해 보겠습니다:

* `property` 및 `constructor-arg` 설정에서 명시적인 의존성은 항상 자동 와이어링을 무시합니다. 간단한 속성(원시 데이터 유형, 문자열, 클래스 등)을 자동 와이어링할 수 없습니다(및 해당 간단한 속성의 배열). 이 제한은 의도적으로 설계된 것입니다.
* 자동 와이어링은 명시적인 와이어링보다 정확도가 낮습니다. 앞에서 언급한대로 Spring은 모호한 경우 예상치 못한 결과를 초래할 수 있는 추측을 피하기 위해 주의합니다. Spring 관리 객체 간의 관계는 더 이상 명시적으로 문서화되지 않습니다.
* 와이어링 정보는 Spring 컨테이너에서 문서를 생성할 수 있는 도구에게 제공되지 않을 수 있습니다.
* 컨테이너 내에서 여러 빈 정의가 와이어링하려는 setter 메서드 또는 생성자 인수에 지정한 유형과 일치할 수 있습니다. 배열, 컬렉션 또는 `Map` 인스턴스의 경우 이는 문제가 아닐 수 있지만, 단일 값을 기대하는 종속성의 경우 이 모호성은 임의로 해결되지 않습니다. 고유한 빈 정의가 없는 경우 예외가 발생합니다.

후자의 경우 여러 옵션이 있습니다.:

* 명시적인 연결을 위해 autowiring을 포기합니다.
* `autowire-candidate` 속성을 `false` 로 설정하여 해당 빈 정의의 autowiring을 피합니다. 자세한 내용은 xref:core/beans/dependencies/factory-autowire.adoc#beans-factory-autowire-candidate[next section]을 참조하세요.
* `<bean/>` 요소의 `primary` 속성을 `true`로 설정하여 단일 빈 정의를 주요 후보로 지정합니다.
* xref:core/beans/annotation-config.adoc[Annotation-based Container Configuration]에서 설명하는 주석 기반 구성을 통해 더 정교한 제어를 구현합니다.


[[beans-factory-autowire-candidate]]
== Excluding a Bean from Autowiring

빈 단위로 자동 배선에서 특정 빈을 제외할 수 있습니다. Spring의 XML 형식에서는 `<bean/>` 요소의 `autowire-candidate` 속성을 `false`로 설정합니다. 이렇게 하면 해당 빈 정의가 자동 배선 인프라(포함하여 xref:core/beans/annotation-config/autowired.adoc[`@Autowired`]와 같은 주석 스타일 구성)에 사용할 수 없게 됩니다.

NOTE: `autowire-candidate` 속성은 유형 기반 자동 배선에만 영향을 미치도록 설계되었습니다. 이름으로 명시적인 참조에는 영향을 미치지 않으며 지정된 빈이 자동 배선 후보로 표시되지 않더라도 해당 이름과 일치하는 경우에도 참조가 해결됩니다. 따라서 이름별 자동 배선은 이름이 일치하는 경우에도 빈을 주입합니다.

빈 이름과의 패턴 일치에 따라 자동 배선 후보를 제한할 수도 있습니다. 
최상위 `<beans/>` 요소는 `default-autowire-candidates` 속성 내에서 하나 이상의 패턴을 허용합니다. 
예를 들어, 이름이 `Repository`로 끝나는 모든 빈에 대한 자동 배선 후보 상태를 제한하려면 `*Repository` 값을 제공하면 됩니다. 
여러 패턴을 제공하려면 쉼표로 구분된 목록으로 정의하십시오. 
빈 정의의 `autowire-candidate` 속성에 대한 명시적인 값 `true` 또는 `false`는 항상 우선합니다. 이러한 빈에 대해서는 패턴 일치 규칙이 적용되지 않습니다.

이러한 기술은 다른 빈에 의해 자동 배선을 받지 않길 원치 않는 빈에 유용합니다. 
이것은 제외된 빈이 자동 배선을 사용하여 구성되지 않는다는 것을 의미하는 것이 아니라 빈 자체가 다른 빈에 대한 자동 배선 후보가 아님을 의미합니다.

---

[[beans-factory-autowire]]
= Autowiring Collaborators

The Spring container can autowire relationships between collaborating beans. You can
let Spring resolve collaborators (other beans) automatically for your bean by
inspecting the contents of the `ApplicationContext`. Autowiring has the following
advantages:

* Autowiring can significantly reduce the need to specify properties or constructor
  arguments. (Other mechanisms such as a bean template
  xref:core/beans/child-bean-definitions.adoc[discussed elsewhere in this chapter] are also valuable
  in this regard.)
* Autowiring can update a configuration as your objects evolve. For example, if you need
  to add a dependency to a class, that dependency can be satisfied automatically without
  you needing to modify the configuration. Thus autowiring can be especially useful
  during development, without negating the option of switching to explicit wiring when
  the code base becomes more stable.

When using XML-based configuration metadata (see xref:core/beans/dependencies/factory-collaborators.adoc[Dependency Injection]), you
can specify the autowire mode for a bean definition with the `autowire` attribute of the
`<bean/>` element. The autowiring functionality has four modes. You specify autowiring
per bean and can thus choose which ones to autowire. The following table describes the
four autowiring modes:

[[beans-factory-autowiring-modes-tbl]]
.Autowiring modes
[cols="20%,80%"]
|===
| Mode| Explanation

| `no`
| (Default) No autowiring. Bean references must be defined by `ref` elements. Changing
  the default setting is not recommended for larger deployments, because specifying
  collaborators explicitly gives greater control and clarity. To some extent, it
  documents the structure of a system.

| `byName`
| Autowiring by property name. Spring looks for a bean with the same name as the
  property that needs to be autowired. For example, if a bean definition is set to
  autowire by name and it contains a `master` property (that is, it has a
  `setMaster(..)` method), Spring looks for a bean definition named `master` and uses
  it to set the property.

| `byType`
| Lets a property be autowired if exactly one bean of the property type exists in
  the container. If more than one exists, a fatal exception is thrown, which indicates
  that you may not use `byType` autowiring for that bean. If there are no matching
  beans, nothing happens (the property is not set).

| `constructor`
| Analogous to `byType` but applies to constructor arguments. If there is not exactly
  one bean of the constructor argument type in the container, a fatal error is raised.
|===

With `byType` or `constructor` autowiring mode, you can wire arrays and
typed collections. In such cases, all autowire candidates within the container that
match the expected type are provided to satisfy the dependency. You can autowire
strongly-typed `Map` instances if the expected key type is `String`. An autowired `Map`
instance's values consist of all bean instances that match the expected type, and the
`Map` instance's keys contain the corresponding bean names.


[[beans-autowired-exceptions]]
== Limitations and Disadvantages of Autowiring

Autowiring works best when it is used consistently across a project. If autowiring is
not used in general, it might be confusing to developers to use it to wire only one or
two bean definitions.

Consider the limitations and disadvantages of autowiring:

* Explicit dependencies in `property` and `constructor-arg` settings always override
  autowiring. You cannot autowire simple properties such as primitives,
  `Strings`, and `Classes` (and arrays of such simple properties). This limitation is
  by-design.
* Autowiring is less exact than explicit wiring. Although, as noted in the earlier table,
  Spring is careful to avoid guessing in case of ambiguity that might have unexpected
  results. The relationships between your Spring-managed objects are no longer
  documented explicitly.
* Wiring information may not be available to tools that may generate documentation from
  a Spring container.
* Multiple bean definitions within the container may match the type specified by the
  setter method or constructor argument to be autowired. For arrays, collections, or
  `Map` instances, this is not necessarily a problem. However, for dependencies that
  expect a single value, this ambiguity is not arbitrarily resolved. If no unique bean
  definition is available, an exception is thrown.

In the latter scenario, you have several options:

* Abandon autowiring in favor of explicit wiring.
* Avoid autowiring for a bean definition by setting its `autowire-candidate` attributes
  to `false`, as described in the xref:core/beans/dependencies/factory-autowire.adoc#beans-factory-autowire-candidate[next section].
* Designate a single bean definition as the primary candidate by setting the
  `primary` attribute of its `<bean/>` element to `true`.
* Implement the more fine-grained control available with annotation-based configuration,
  as described in xref:core/beans/annotation-config.adoc[Annotation-based Container Configuration].



[[beans-factory-autowire-candidate]]
== Excluding a Bean from Autowiring

On a per-bean basis, you can exclude a bean from autowiring. In Spring's XML format, set
the `autowire-candidate` attribute of the `<bean/>` element to `false`. The container
makes that specific bean definition unavailable to the autowiring infrastructure
(including annotation style configurations such as xref:core/beans/annotation-config/autowired.adoc[`@Autowired`]
).

NOTE: The `autowire-candidate` attribute is designed to only affect type-based autowiring.
It does not affect explicit references by name, which get resolved even if the
specified bean is not marked as an autowire candidate. As a consequence, autowiring
by name nevertheless injects a bean if the name matches.

You can also limit autowire candidates based on pattern-matching against bean names. The
top-level `<beans/>` element accepts one or more patterns within its
`default-autowire-candidates` attribute. For example, to limit autowire candidate status
to any bean whose name ends with `Repository`, provide a value of `*Repository`. To
provide multiple patterns, define them in a comma-separated list. An explicit value of
`true` or `false` for a bean definition's `autowire-candidate` attribute always takes
precedence. For such beans, the pattern matching rules do not apply.

These techniques are useful for beans that you never want to be injected into other
beans by autowiring. It does not mean that an excluded bean cannot itself be configured by
using autowiring. Rather, the bean itself is not a candidate for autowiring other beans.



