[[beans-factory-lazy-init]]
= Lazy-initialized Beans

기본적으로 `ApplicationContext` 구현은 모든 xref:core/beans/factory-scopes.adoc#beans-factory-scopes-singleton[싱글톤] 빈을 초기화 프로세스의 일부로 미리 생성하고 구성합니다. 
일반적으로 이러한 미리 인스턴스화는 구성 또는 주변 환경의 오류를 즉시 발견하기 때문에 바람직합니다. 그러나 이 동작이 원하지 않는 경우 싱글톤 빈의 빈 정의를 지연 초기화로 표시하여 미리 인스턴스화를 방지할 수 있습니다. 
지연 초기화된 빈은 IoC 컨테이너에게 빈 인스턴스를 처음 요청할 때 생성하도록 지시합니다.

XML에서 이 동작은 `<bean/>` 요소의 `lazy-init` 속성으로 제어됩니다. 다음 예제에서와 같이:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="lazy" class="com.something.ExpensiveToCreateBean" lazy-init="true"/>
	<bean name="not.lazy" class="com.something.AnotherBean"/>
----

위의 구성이 `ApplicationContext`에서 사용될 때, `lazy` 빈은 `ApplicationContext`가 시작될 때 미리 인스턴스화되지 않으며, `not.lazy` 빈은 미리 인스턴스화됩니다.

그러나 지연 초기화된 빈이 지연 초기화되지 않은 싱글톤 빈의 종속성일 때 `ApplicationContext`는 시작될 때 지연 초기화된 빈을 생성합니다.
이는 싱글톤의 종속성을 충족해야 하기 때문입니다. 지연 초기화된 빈은 다른 지연 초기화되지 않은 싱글톤 빈에 주입됩니다.

컨테이너 수준에서도 지연 초기화를 제어할 수 있으며, 이를 위해 `<beans/>` 요소의 `default-lazy-init` 속성을 사용할 수 있습니다. 
다음 예제를 참조하세요:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans default-lazy-init="true">
		<!-- no beans will be pre-instantiated... -->
	</beans>
----

---

[[beans-factory-lazy-init]]
= Lazy-initialized Beans

By default, `ApplicationContext` implementations eagerly create and configure all
xref:core/beans/factory-scopes.adoc#beans-factory-scopes-singleton[singleton] beans as part of the initialization
process. Generally, this pre-instantiation is desirable, because errors in the
configuration or surrounding environment are discovered immediately, as opposed to hours
or even days later. When this behavior is not desirable, you can prevent
pre-instantiation of a singleton bean by marking the bean definition as being
lazy-initialized. A lazy-initialized bean tells the IoC container to create a bean
instance when it is first requested, rather than at startup.

In XML, this behavior is controlled by the `lazy-init` attribute on the `<bean/>`
element, as the following example shows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="lazy" class="com.something.ExpensiveToCreateBean" lazy-init="true"/>
	<bean name="not.lazy" class="com.something.AnotherBean"/>
----

When the preceding configuration is consumed by an `ApplicationContext`, the `lazy` bean
is not eagerly pre-instantiated when the `ApplicationContext` starts,
whereas the `not.lazy` bean is eagerly pre-instantiated.

However, when a lazy-initialized bean is a dependency of a singleton bean that is
not lazy-initialized, the `ApplicationContext` creates the lazy-initialized bean at
startup, because it must satisfy the singleton's dependencies. The lazy-initialized bean
is injected into a singleton bean elsewhere that is not lazy-initialized.

You can also control lazy-initialization at the container level by using the
`default-lazy-init` attribute on the `<beans/>` element, as the following example shows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans default-lazy-init="true">
		<!-- no beans will be pre-instantiated... -->
	</beans>
----



