[[beans-factory-dependson]]
= Using `depends-on`

하나의 빈이 다른 빈의 종속성이라는 것은 일반적으로 하나의 빈이 다른 빈의 속성으로 설정되었다는 것을 의미합니다. 
일반적으로 이를 수행하기 위해 XML 기반 구성 메타데이터에서는 <<beans-ref-element, `<ref/>` 요소>>를 사용합니다.
그러나 때로는 빈 간의 종속성이 덜 직접적인 경우도 있습니다. 
예를 들어 클래스의 정적 초기화자가 데이터베이스 드라이버 등록과 같이 트리거되어야 하는 경우가 있습니다. 
`depends-on` 속성은 이 요소를 사용하는 빈이 초기화되기 전에 하나 이상의 빈이 명시적으로 초기화되도록 강제할 수 있습니다. 
다음 예제는 `depends-on` 속성을 사용하여 단일 빈에 대한 종속성을 표현합니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="beanOne" class="ExampleBean" depends-on="manager"/>
	<bean id="manager" class="ManagerBean" />
----

여러 개의 빈에 대한 종속성을 표현하려면 `depends-on` 속성의 값으로 빈 이름 목록을 제공하면 됩니다 
(쉼표, 공백 및 세미콜론은 유효한 구분자입니다):

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="beanOne" class="ExampleBean" depends-on="manager,accountDao">
		<property name="manager" ref="manager" />
	</bean>

	<bean id="manager" class="ManagerBean" />
	<bean id="accountDao" class="x.y.jdbc.JdbcAccountDao" />
----

NOTE: `depends-on` 속성은 초기화 시간 종속성과 xref:core/beans/factory-scopes.adoc#beans-factory-scopes-singleton[싱글톤] 빈의 경우에만 해당되는 파괴 시간 종속성을 모두 지정할 수 있습니다. 
`depends-on` 관계를 정의하는 종속 빈은 주어진 빈이 파괴되기 전에 먼저 파괴됩니다. 따라서 `depends-on`은 종료 순서도 제어할 수 있습니다.

---

[[beans-factory-dependson]]
= Using `depends-on`

If a bean is a dependency of another bean, that usually means that one bean is set as a
property of another. Typically you accomplish this with the <<beans-ref-element, `<ref/>`
element>> in XML-based configuration metadata. However, sometimes dependencies between
beans are less direct. An example is when a static initializer in a class needs to be
triggered, such as for database driver registration. The `depends-on` attribute can
explicitly force one or more beans to be initialized before the bean using this element
is initialized. The following example uses the `depends-on` attribute to express a
dependency on a single bean:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="beanOne" class="ExampleBean" depends-on="manager"/>
	<bean id="manager" class="ManagerBean" />
----

To express a dependency on multiple beans, supply a list of bean names as the value of
the `depends-on` attribute (commas, whitespace, and semicolons are valid
delimiters):

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="beanOne" class="ExampleBean" depends-on="manager,accountDao">
		<property name="manager" ref="manager" />
	</bean>

	<bean id="manager" class="ManagerBean" />
	<bean id="accountDao" class="x.y.jdbc.JdbcAccountDao" />
----

NOTE: The `depends-on` attribute can specify both an initialization-time dependency and,
in the case of xref:core/beans/factory-scopes.adoc#beans-factory-scopes-singleton[singleton] beans only, a corresponding
destruction-time dependency. Dependent beans that define a `depends-on` relationship
with a given bean are destroyed first, prior to the given bean itself being destroyed.
Thus, `depends-on` can also control shutdown order.



